.PHONY: Mp3SourceTests RemoteListenerTests clean
all: Mp3SourceTests RemoteListenerTests

Mp3SourceTests:
	$(MAKE) -C Mp3Source

RemoteListenerTests:
	$(MAKE) -C RemoteListener

clean:
	$(MAKE) -C Mp3Source clean
	$(MAKE) -C RemoteListener clean
